name: Black

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U black
      - name: Run black
        run: black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Auto fixes"
            commit_options: "--no-verify"
            repository: .
            commit_user_name: ArdNeriw003
            commit_user_email: ArdNeriw003@users.noreply.github.com
            commit_author: ArdNeriw003<Ard_Neriw003@users.noreply.github.com>
